[package]
name = "ecosystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"

[dev-dependencies]
anyhow = "1.0.86"
derive_builder = "0.20.0"
derive_more = "0.99.18"
