### index handler

GET http://localhost:8081/

### update handler

PATCH http://localhost:8080/
Content-Type: application/json

{
  "age": 20,
  "skills": [
    "rust",
    "go",
    "typescript"
  ]
}

### url shorten
POST http://localhost:9898/
Content-Type: application/json

{
  "url": "https://docs.rs/axum/latest/axum/response/trait.IntoResponse.html"
}

### url redirect
GET http://localhost:9898/7Yh_zJ